# Generated by Django 6.0.2 on 2026-03-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0003_alter_product_price_order_orderelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время и дата заказа'),
        ),
    ]
