# Generated by Django 6.0.2 on 2026-03-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0005_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
